export const testingHands = [
  {
    hand: "AH AD 2H 3H 4H",
    fifteenScore: 0,
    flushScore: 0,
    nobsScore: 0,
    pairScore: 2,
    runScore: 8,
  },
  {
    hand: "AH 2D 3H 4H 5H",
    fifteenScore: 2,
    flushScore: 0,
    nobsScore: 0,
    pairScore: 0,
    runScore: 5,
  },
  {
    hand: "8H 7H 8D 7D 7C",
    fifteenScore: 12,
    flushScore: 0,
    nobsScore: 0,
    pairScore: 8,
    runScore: 0,
  },
  {
    hand: "6H 7H 7D 8H 9H",
    fifteenScore: 6,
    flushScore: 0,
    nobsScore: 0,
    pairScore: 2,
    runScore: 8,
  },
  {
    hand: "5H 5S 5D JC 5C",
    fifteenScore: 16,
    flushScore: 0,
    nobsScore: 1,
    pairScore: 12,
    runScore: 0,
  },
];
